# Generated by Django 4.0.1 on 2022-01-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='daet',
            new_name='date',
        ),
    ]
