# Generated by Django 4.0.1 on 2022-01-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_daet_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mobile',
            new_name='phone',
        ),
    ]
