# Generated by Django 4.0.1 on 2022-02-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_rename_mobile_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news'),
        ),
    ]
